=begin
#Rakam API Documentation

#An analytics platform API that lets you create your own analytics services.

OpenAPI spec version: 0.5
Contact: contact@rakam.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for RakamClient::UseractionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UseractionApi' do
  before do
    # run before each test
    @instance = RakamClient::UseractionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UseractionApi' do
    it 'should create an instact of UseractionApi' do
      expect(@instance).to be_instance_of(RakamClient::UseractionApi)
    end
  end

  # unit tests for batch
  # Apply batch operation
  # 
  # @param user_email_action_batch 
  # @param [Hash] opts the optional parameters
  # @return [Integer]
  describe 'batch test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send
  # Perform action for single user
  # 
  # @param user_email_action_send 
  # @param [Hash] opts the optional parameters
  # @return [BOOLEAN]
  describe 'send test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
